### ISSUE TITLE
Alternatives to the Ranged Script Number (RSN) format

### ISSUE THREAD

**Issue by zander** [bitjson/pmv3#4]
Copying the long explanation from [here](https://bitcoincashresearch.org/t/cashtokens-pmv3-fixed-size-inductive-proofs-transaction-integer-compatibility/265/34?u=tom);

Here the arguments, as I understand it, for changing the transaction formats parts which encode numbers:

* The current transaction format has 3 different ways to encode integers. You name 4 as you include the one inside of the script as well.
* The idea to replace all with one is attractive from a purely architectural point of view.
* Bitcoin Script has severe problems with the var-width encoding when doing covenants.
* Variable-width encoding gains in tx size are a couple of percent.
* Variable width means that the ‘amount’ field can grow beyond the 64-bit limit it has today.  
 Caveat is that the 21 million limit we have today only takes 6½ bytes. We could multiply it with 8196 without needing more bytes.

So, really the main reason you suggested this is because Bitcoin Script doesn’t understand one of the 3 used integer formats. The var-int. And your suggestion is for the rest of the transaction to use the integer encoding that the scritping VM already is familiar with.

So, I have a counter suggestion. Two actually.

# Use a more common encoding scheme.

My thinking here is that interpreting transactions, at least at the basic level, is going to be something that a LOT of software libraries will do. On the other hand the amount of places that implement a VM will be much lower. Probably only the full nodes and some specialized software.

Based on this, I vastly prefer to solve your basic problem of Bitcoin Script not understanding the format by introducing two opcodes. One for each of the conversion directions and picking a format that is actually much more standardized. See Variable-width encoding - Wikipedia 1. Think UTF-8 as an example of this.

Now, if you are going to break 100% of all transaction parsing code-bases, I think it makes a lot of sense to include a little upgrade that makes future transaction format changes much easier. This is based on reseach I did some years ago in the project called “Flextrans”.

The basic idea is that each field becomes a “name / format / value” type. This allows inserting new data in the transaction at a later version without forcing everyone to AGAIN rewrite the entire transaction parsing. Just like adding a new html tag to the standard doesn’t require you to update the old parsers.

This thinking got me to suggestion two:

# Use the current size-formats.

So, we can go fancy and require everyone to rewrite the format, while also requiring two new opcodes to do the conversion between tx-numbers and script-vm-numbers.
But, hang on. If you need those opcodes anyway, then why would we change the numbering format?

I liked (and still do) the FlexTrans approach. But the gains are small and the change intrusive.

I’d vastly prefer to not have a different numbering format and simply add two opcodes for the conversion.

**Comment by zander** [comment]
(copy from the bitcoincashresearch)

As a followup and to make things more concrete I have the following suggestion for your proposal.

I would like to split the proposal into two parts with the aim to simplify activation and to make sure that we have a smaller change that I believe can reach consensus next May.
The actual changes in the transaction format would then become this;

* 2022-05. Transaction v3 introduced, where needed the input-script is replaced with a 32-byte hash and appended to the transaction is the list of detached proofs.  
When it comes to the transaction format, this is the only change. This actually does unlock your many improvements and inductive proofs. It allows Script to look backwards in time. It enables tokens and it enables most of your cool examples scripts. Other scripting improvements are a separate CHIP.

* 2023: Transaction v4 introduced for variable-int sizes and various other ideas (tbd).  
Variable int sizes is one of the ideas you separately came up with which was previously part of FlexTrans ([BIP 134](https://en.bitcoin.it/wiki/BIP_0134)), there were some other neat ideas that would be useful to combine in such a transaction format change.


The direct result of seperating your one CHIP is that parsers that read current (v2) style transactions will very likely not need to be modified to accept v3 transactions. Afterall, you just add some more data to the end. Even TXID calculation is going to be unchanged.
This is going to make deployment much simpler and since the May 2022 upgrade already has a large number of proposals I think it makes sense to keep it simple.

Changing the integer-format (the var-int idea) in transactions is simply a much more invasive change, 100% of the existing transaction-parsing code will need to get support that and for that it really makes sense to wait until after [Restrict Transaction Version](https://gitlab.com/bitcoin.cash/chips/-/blob/master/CHIP-2021-01-Restrict%20Transaction%20Versions.md) has activated which is specifically meant to make this kind of deployments simpler. Hence the suggestion to push it forward.

So, the separation of those more invasive transaction changes out of the detached signature change would be nice to move to the upgrade of 2023 to give ourselves as well as the wider ecosystem plenty of time to get it right.

**Comment by scherrey** [comment]
I agree with breaking the proposal apart but not necessarily the order/priorities. Making improved numerics independent of the PMV3 simply makes good sense. PMV3 is a really complex proposal on its own (albeit to accomplish some really important things) and needs to stand on its own. But I also think to actualize PMV3's benefits in real-world applications crucially depends upon better numerics and better math. I just think we should make those independent but parallel efforts. We should be able to implement such a thing and get it on test nets for some real working experience with strong implementations in core products in plenty of time for May 2022. Let's not assume it has to come after. Indeed I'd make a fairly strong case that it be a pre-requisite for deploying PMV3 (or something similar). But yeah - let's not force either until they're properly ready to go. But I hope we can have both by May 2022.

**Comment by bitjson** [comment]
Hey @zander and @scherrey, thanks for all your help and review so far! I just finished extracting the RSN format components into their own [`CHIP-2021-01-RSN: Ranged Script Number Format`](https://github.com/bitjson/pmv3/blob/master/ranged-script-numbers.md), please let me know what you think! There's [a changelog](https://github.com/bitjson/pmv3#changelog) now too. (And here's the commit if you'd like to review the line-by-line changes: https://github.com/bitjson/pmv3/commit/0a62c6687702921263aa77bf857e44bcc2e731ad)

I think I'll leave this issue open so we can talk more about @zander's suggestions above? And maybe we can change the title now that the RSN stuff has its own CHIP.

**Comment by bitjson** [comment]
To kick off talking about it: I updated the `Use of RSN Format` section in the PMv3 CHIP to be more thorough (snippet below). 

---

### Use of RSN Format

The [`Ranged Script Number` (RSN)](https://github.com/bitjson/pmv3/blob/master/ranged-script-numbers.md) format is chosen for its ease of conversion to and from standard Script Numbers within contracts. The VM Script Number format is already consensus-critical, so it is less disruptive to migrate transaction format integer types to the Script Number format than to migrate the reverse.

One alternative solution is to implement `OP_NUM2VARINT` and `OP_VARINT2NUM` operations. While this would allow for slightly better compression of `VarInt`s between `128` and `252` (2 bytes), in practice, relatively few transactions use those numbers for input count, output count, or bytecode lengths. (This inefficiency is also dwarfed by the space savings of compressing `Version` [3 bytes], `Outpoint Index` [approx. 3 bytes per input], and output `Value` [2-7 bytes per output].)

An opcode-only solution would increase the size and complexity of contracts (which would still need [strategies for splitting/parsing VarInt values from stack items](https://github.com/bitjson/pmv3/blob/master/ranged-script-numbers.md#usage-comparison-vs-varint)), complicate the VM model (by introducing a completely new number "type" requiring bitwise manipulation), and require future contract compilers and wallets to include software support for the VarInt format (which is otherwise unnecessary for new wallet applications).

Because contract compilers and wallets are already required to support the `Script Number` format when creating and interacting with complex contracts, implementation of the `Ranged Script Number` format is less burdensome for these applications. (Of course, less advanced wallets can continue to use v1/v2 transactions.)

> Note, many other P2P protocol messages use other integer formats, and these remain unchanged. This includes the P2P protocol `tx` message header, which will continue to use the standard 24-byte header format.

---

@zander I also did a lot more thinking about usage in contracts here: [`Usage Comparison vs. VarInt`](https://github.com/bitjson/pmv3/blob/master/ranged-script-numbers.md#usage-comparison-vs-varint). In short, I think the VarInt format is significantly more complex – and saddles us with more long-term technical debt in contract-land – than some other system based on Script Numbers (doesn't necessarily need to be this RSN construction, I'm very open to other ideas). 

But I'd love to hear your thoughts on it given all that new info 😄
