### ISSUE TITLE
Zero size input-script creates tech-debt

### ISSUE THREAD

**Issue by zander** [bitjson/pmv3#8]
Yesterday I was pointed out something I read past, the input-script is said to have a zero size in order to have a 32-byte hash following it.

This creates a technical debt, a hack that requires special handling that, especially in general purpose systems like Satoshis client, will not be easy to integrate.

My first idea was that the count is a 32, but I realize why you did this as that makes differentiation between one type and the other a guess, not a certainty.

As such I don't have a solution for this. It is going to be a major issue if you look at `serialize.h` and check vector serialization.

**Comment by bitjson** [comment]
Hey, thanks for the issue! This makes me significantly more confident that the spec is being adequately reviewed 😄

I'm also not very happy with using `0x00` as the boolean switch there – I think it would be better to use a value which cannot possibly be confused with a length. (And `0` could be a reasonable length value if fields were somehow to be excluded in the future.)

So instead we could use:

- `-0` (`0x80`) – though `0` really should equal `-0`, and (very poorly-tested) implementations might still confuse the two.
- `-1` (`0x81`) – this is the first negative value which can't reasonably be confused for a byte length.
- `-32` (`0xa0`) – this one is interesting because it would also indicate the length, but the negative value works as the boolean switch. This would possibly allow future upgrades to cleanly specify different size hashes.

I'm leaning toward `0xa0`, since `0xa0` and `0x81` are basically equivalent as flags, but `0xa0` leaves it more open for future upgrades to create logical consistency.

On deserializing in the C++ implementations: is there a reason it would be left to the serialization utilities in `serialize.h`? I imagine maintainers would want to do a bit of refactoring, but I expected the conditional to be at the `CTransaction` "deserialize" method level, where deserialize for v3 transactions would include a branch for `0xa0` which then reads the fixed 32 bytes. There are several other slight differences (like version only being 1 byte) where deserialization will differ already, so I've been assuming most implementations will want to simply use a new method. (Though if you have other ideas for how to do it, I'd love to make v3 parsing look as clean as possible in all the implementations.)
